##### Files Contd..

In [ ]:
fh = open('students.txt')
data = fh.read() # after read it reaches end of file 
print('1',data)
data = fh.read() # there is no content after end of file
print('2',data)
fh.close()

In [ ]:
fh = open('students.txt')

print('Cursor position before read:',fh.tell())
fh.read()
print('Cursor position after read:',fh.tell())

fh.close()

In [ ]:
fh = open('students.txt')

print('Cursor position before read:',fh.tell())
fh.seek(10)
print('Cursor position after seek:',fh.tell())
print('Cursor position after read:\n',fh.read())


fh.close()

#### readline()

In [ ]:
fh = open('students.txt')

fh.readline()
print(fh.readline())

fh.close()

#### readlines()

In [ ]:
fh = open('students.txt')

print(fh.readlines())

fh.close()

In [ ]:
fh = open('students.txt','r+')

fh.write('sairam3')

fh.close()

##### Regular Expressions

In [ ]:
import re

##### 1. re.search(str_pattern,str_data)

In [ ]:
name = 'sairam'
print(re.search('s',name))

In [ ]:
name = 'sairam'
print(re.search('z',name))

In [ ]:
name = 'sairam'
print(re.search('sm',name))

In [ ]:
name = 'sairam'
print(re.search('a',name))

#### re.match( str_pattern, str_data )

In [ ]:
name = 'sairam'
print(re.match('sai',name))

In [ ]:
name = 'sairam'
print(re.match('a',name))

#### re.findall( str_pattern, str_data )

In [ ]:
name = 'sairam'

print(re.findall('a',name))

### Special Characters in Regular Expressions

#### .  (dot)
    any single character

In [ ]:
print(re.search('.', 'sairam'))

In [ ]:
print(re.search('.', ""))

In [ ]:
print(re.search('...','sairam'))

#### ^ 
    starting with

In [ ]:
print(re.search('^s','sairam'))

In [ ]:
print(re.search('^i','sairam'))

In [ ]:
print(re.search('^.','sairam'))

#### $

    ending with

In [ ]:
print(re.search('m$','sairam'))

In [ ]:
print(re.search('a$','sairam'))

In [ ]:
print(re.search('^s....m$','sairam'))

In [ ]:
name1 = 'sairam' # match
name2 = 'sreeram' # match
name3 = 'ram' # None
name4 = 'raam' # match
print(re.search('...m$',name1))
print(re.search('...m$',name2))
print(re.search('...m$',name3))
print(re.search('...m$',name4))

##### filter data which has end with s and must and should 6 characters using RegularExpressions

In [ ]:
names = ['apples','oranges','grapes','bananas','lemons']
for item in names:
    if re.search('^.....s$',item):
        print(item)

#### {min,max}

In [ ]:
print(re.search('a{4}','aaaaa'))

In [ ]:
print(re.search('a{4}','aaa'))

In [ ]:
print(re.search('a{3,7}','aa'))
print(re.search('a{3,7}','aaa'))
print(re.search('a{3,7}','aaaa'))
print(re.search('a{3,7}','aaaaaaa'))
print(re.search('a{3,7}','aaaaaaaa'))

In [ ]:
print(re.search('^a{3,7}$','aaaaaaaa'))

#### \d  any single digit

In [ ]:
print(re.search('\d','sairam123'))

#### Indian mobile number validation

##### conditions:

1. must contain 10 digits
2. must startswith 9,8,7,6

In [ ]:
print(re.search('^\d{10}$','1234567890'))
print(re.search('^\d{10}$','12345678901'))
print(re.search('^\d{10}$','12345670'))

#### [6789]

In [ ]:
print(re.search('[6-9]','sai982123'))

In [ ]:
print(re.search('[a-k]','sai982123'))

##### [^]

In [ ]:
print(re.search('[^abc]','abcxyz'))

In [ ]:
print(re.search('^[6-9]\d{9}$','9848022338'))
print(re.search('^[6-9]\d{9}$','5848022338'))

##### find sum of digits in data using regular expression

In [ ]:
web_content = """
abc 123
hi 456 hello78
thanks
"""
numbers_list = re.findall('\d',web_content)
print(numbers_list)
result = list(map(int,numbers_list))
print(sum(result))

In [ ]:
web_content = """
abc 123
hi 456 hello78
thanks
"""
char_list = re.findall('[a-zA-Z]',web_content)
print(char_list)
print(len(char_list))

##### \D other than any single digit

In [ ]:
print(re.search('\D','123sai'))

In [ ]:
web_content = """
abc 123
hi 456 hello78
thanks
"""
print(len(web_content))
print(len(re.findall('\D',web_content)))

##### \s select spacing characters

In [ ]:
web_content = """
abc 123
hi 456 hello78
thanks
"""

print(re.findall('\s',web_content))

##### \S otherthan spacing characters

In [ ]:
web_content = """
abc 123
hi 456 hello78
thanks
"""

print(re.findall('\S',web_content))

#### \w 
    it selects the characters a-z,A-Z,0-9,_ 

In [ ]:
print(re.search('\w','   sai'))

#### \W
    otherthan \w

In [ ]:
print(re.search('\W','sdfsd   sai'))

## *
    zero or more

In [ ]:
print(re.search('a*','aaaaabaaa'))

In [ ]:
print(re.search('z*','aaaaabaaa'))

In [ ]:
print(re.search('b*','aaaaabaaa'))

#### select the data which contain starting s and ending i

In [ ]:
name1 = 'si'
name2 = 'saai'
name3 = 'sreei'
print(re.search('^s.*i$',name1))
print(re.search('^s.*i$',name2))
print(re.search('^s.*i$',name3))

In [ ]:
print(re.search('^s*i$','si'))

In [ ]:
print(re.search('^s*i$','ssssi'))

In [ ]:
print(re.search('^s*.i$','sssbi'))

### +

    one or more

In [ ]:
print(re.search('a+','bbbaaaccaa'))

In [ ]:
name1 = 'si'
name2 = 'saai'
name3 = 'sreei'
print(re.search('^s.+i$',name1))
print(re.search('^s.+i$',name2))
print(re.search('^s.+i$',name3))

### working with modules
    python module is a python file contains function,variables and valid 
    python statements


In [ ]:
import project

In [ ]:
project.welcome('sairam')

In [ ]:
project.add(3,5)

In [ ]:
project.PI

## Numpy

In [8]:
A = [[1,2],[3,4]]

B = [[3,4],[4,5]]

C = []

for row_index in range(len(A)):
    row1 = A[row_index] 
    row2 = B[row_index]
    item1 = row1[0]+row2[0]
    item2 = row1[1] + row2[1]
    C.append([item1,item2])

print(A)
print(B)
print('\n')
print(C)


[[1, 2], [3, 4]]
[[3, 4], [4, 5]]


[[4, 6], [7, 9]]


In [9]:
import numpy as np

In [11]:
values = [1,2,3]
a1 = np.array(values)
print(a1)

[1 2 3]


In [12]:
a1[0]

1

In [13]:
a1[2]

3

#### Shape of the array

In [16]:
a1.shape

(3,)

In [18]:
values = [[1,2,3],[4,5,6]]

a2 = np.array(values)
print(a2)
print(a2.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [20]:
values1 = [[1,2],[3,4]]
a1 = np.array(values1)
values2 = [[2,1],[4,3]]
a2 = np.array(values2)
print(a1)
print()
print(a2)

[[1 2]
 [3 4]]

[[2 1]
 [4 3]]


In [22]:
a1 += 2
print(a1)

[[3 4]
 [5 6]]


In [23]:
a1[0]

array([3, 4])

In [25]:
print(a1[0][0])
a1[0][0] = 10
print(a1[0][0])

3
10


In [26]:
print(a1)
print()
print(a2)

[[10  4]
 [ 5  6]]

[[2 1]
 [4 3]]


In [27]:
a1 + a2 

array([[12,  5],
       [ 9,  9]])

In [28]:
a1 - a2

array([[8, 3],
       [1, 3]])

In [29]:
a1 * a2

array([[20,  4],
       [20, 18]])

In [30]:
a1.dot(a2)

array([[36, 22],
       [34, 23]])

In [31]:
a1

array([[10,  4],
       [ 5,  6]])

In [32]:
a2

array([[2, 1],
       [4, 3]])

In [33]:
print(np.arange(10))

[0 1 2 3 4 5 6 7 8 9]


In [34]:
print(np.arange(1,10,2))

[1 3 5 7 9]


In [35]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [36]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [37]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [40]:
one = np.ones((2,8))
one

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

In [41]:
one.reshape(4,4)

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])